# Generated by Django 3.2.5 on 2021-07-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievementid', models.IntegerField(db_column='AchievementID', primary_key=True, serialize=False)),
                ('achievement', models.CharField(db_column='Achievement', max_length=75)),
                ('achievementdescription', models.TextField(db_column='AchievementDescription')),
                ('achivementdate', models.CharField(db_column='AchivementDate', max_length=100)),
                ('username', models.CharField(db_column='Username', max_length=50)),
            ],
            options={
                'db_table': 'tAchievements',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationid', models.IntegerField(db_column='EducationID', primary_key=True, serialize=False)),
                ('university', models.CharField(db_column='University', max_length=100)),
                ('startmonth', models.CharField(blank=True, db_column='StartMonth', max_length=15, null=True)),
                ('endmonth', models.CharField(blank=True, db_column='EndMonth', max_length=15, null=True)),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('gpa', models.FloatField(blank=True, db_column='GPA', null=True)),
                ('honors', models.CharField(blank=True, db_column='Honors', max_length=50, null=True)),
                ('degreename', models.CharField(blank=True, db_column='DegreeName', max_length=100, null=True)),
                ('endyear', models.CharField(db_column='EndYear', max_length=4)),
                ('startyear', models.CharField(db_column='StartYear', max_length=4)),
            ],
            options={
                'db_table': 'tEducation',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('employmentid', models.IntegerField(db_column='EmploymentID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('employer', models.CharField(db_column='Employer', max_length=100)),
                ('role', models.CharField(db_column='Role', max_length=75)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('state', models.CharField(db_column='State', max_length=50)),
                ('startmonth', models.CharField(blank=True, db_column='StartMonth', max_length=15, null=True)),
                ('startyear', models.CharField(blank=True, db_column='StartYear', max_length=4, null=True)),
                ('endmonth', models.CharField(blank=True, db_column='EndMonth', max_length=15, null=True)),
                ('endyear', models.CharField(blank=True, db_column='EndYear', max_length=4, null=True)),
                ('iscurrent', models.TextField(blank=True, db_column='IsCurrent', null=True)),
            ],
            options={
                'db_table': 'tEmployment',
            },
        ),
        migrations.CreateModel(
            name='JobDescriptions',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('employmentid', models.IntegerField(db_column='EmploymentID')),
                ('jobdescription', models.TextField(db_column='JobDescription')),
            ],
            options={
                'db_table': 'tJobDescriptions',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid', models.IntegerField(db_column='ProjectID', primary_key=True, serialize=False)),
                ('projectname', models.CharField(db_column='ProjectName', max_length=100)),
                ('projectdescription', models.TextField(db_column='ProjectDescription')),
                ('startmonth', models.CharField(db_column='StartMonth', max_length=15)),
                ('endmonth', models.CharField(blank=True, db_column='EndMonth', max_length=15, null=True)),
                ('completed', models.TextField(db_column='Completed')),
                ('username', models.CharField(db_column='Username', max_length=50)),
                ('startyear', models.CharField(db_column='StartYear', max_length=4)),
                ('endyear', models.CharField(db_column='EndYear', max_length=4)),
            ],
            options={
                'db_table': 'tProjects',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('version', models.IntegerField(db_column='Version')),
                ('resumename', models.CharField(db_column='ResumeName', max_length=50)),
                ('resumeid', models.IntegerField(db_column='ResumeID', primary_key=True, serialize=False)),
                ('resumedescription', models.TextField(blank=True, db_column='ResumeDescription', null=True)),
                ('objective', models.TextField(blank=True, db_column='Objective', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tResume',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillid', models.BigIntegerField(db_column='SkillID', primary_key=True, serialize=False)),
                ('skillname', models.CharField(db_column='SkillName', max_length=75)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=15, null=True)),
                ('username', models.CharField(db_column='Username', max_length=20)),
            ],
            options={
                'db_table': 'tSkills',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('linkid', models.IntegerField(db_column='LinkID', primary_key=True, serialize=False)),
                ('linkurl', models.TextField(db_column='LinkURL')),
                ('linktype', models.CharField(blank=True, db_column='LinkType', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tSocialLinks',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('homephone', models.CharField(blank=True, db_column='HomePhone', max_length=13, null=True)),
                ('mobilephone', models.CharField(blank=True, db_column='MobilePhone', max_length=13, null=True)),
                ('streetaddress1', models.CharField(blank=True, db_column='StreetAddress1', max_length=250, null=True)),
                ('streetaddress2', models.CharField(blank=True, db_column='StreetAddress2', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=5, null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='LastUpdated', null=True)),
            ],
            options={
                'db_table': 'tUsers',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteerid', models.IntegerField(db_column='VolunteerID', primary_key=True, serialize=False)),
                ('position', models.CharField(db_column='Position', max_length=75)),
                ('volunteerdescription', models.CharField(db_column='VolunteerDescription', max_length=1500)),
                ('company', models.CharField(db_column='Company', max_length=100)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('state', models.CharField(db_column='State', max_length=50)),
                ('startmonth', models.CharField(blank=True, db_column='StartMonth', max_length=15, null=True)),
                ('endmonth', models.CharField(blank=True, db_column='EndMonth', max_length=15, null=True)),
                ('current', models.TextField(blank=True, db_column='Current', null=True)),
                ('username', models.CharField(db_column='Username', max_length=20)),
                ('startyear', models.CharField(db_column='StartYear', max_length=4)),
                ('endyear', models.CharField(db_column='EndYear', max_length=4)),
            ],
            options={
                'db_table': 'tVolunteer',
            },
        ),
        migrations.CreateModel(
            name='ResumeVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeid', models.ForeignKey(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.resume')),
                ('volunteerid', models.ForeignKey(db_column='VolunteerID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.volunteer')),
            ],
            options={
                'db_table': 'tResumeVolunteer',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('educationid', models.IntegerField(db_column='EducationID')),
            ],
            options={
                'db_table': 'tResumeEducation',
                'unique_together': {('resumeid', 'educationid')},
            },
        ),
        migrations.CreateModel(
            name='ResumeAchievements',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('achievementid', models.IntegerField(db_column='AchievementID')),
            ],
            options={
                'db_table': 'tResumeAchievements',
                'unique_together': {('resumeid', 'achievementid')},
            },
        ),
        migrations.CreateModel(
            name='ResumeSocialLinks',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('linkid', models.ForeignKey(db_column='LinkID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.sociallinks')),
            ],
            options={
                'db_table': 'tResumeSocialLinks',
                'unique_together': {('resumeid', 'linkid')},
            },
        ),
        migrations.CreateModel(
            name='ResumeSkills',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('skillid', models.ForeignKey(db_column='SkillID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.skills')),
            ],
            options={
                'db_table': 'tResumeSkills',
                'unique_together': {('resumeid', 'skillid')},
            },
        ),
        migrations.CreateModel(
            name='ResumeProjects',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('projectid', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.projects')),
            ],
            options={
                'db_table': 'tResumeProjects',
                'unique_together': {('resumeid', 'projectid')},
            },
        ),
        migrations.CreateModel(
            name='ResumeEmployment',
            fields=[
                ('resumeid', models.OneToOneField(db_column='ResumeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='builder.resume')),
                ('employmentid', models.ForeignKey(db_column='EmploymentID', on_delete=django.db.models.deletion.DO_NOTHING, to='builder.employment')),
            ],
            options={
                'db_table': 'tResumeEmployment',
                'unique_together': {('resumeid', 'employmentid')},
            },
        ),
    ]
